import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/context/session";
import Side from "@/components/Bottom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TP 8 - Jugando con banderas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css"/>
      </head>
      <body className={inter.className}>
        <SessionProvider>
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
